services:
    sw1zpr18aml6epqnir0a4o8o-130523890373:
        image: 'sw1zpr18aml6epqnir0a4o8o:a0a298d1c138043af2c3e2417a0c07735213ee31'
        container_name: sw1zpr18aml6epqnir0a4o8o-130523890373
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - sw1zpr18aml6epqnir0a4o8o-130523890373
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-sw1zpr18aml6epqnir0a4o8o.entryPoints=http
            - traefik.http.routers.http-0-sw1zpr18aml6epqnir0a4o8o.middlewares=redirect-to-https
            - 'traefik.http.routers.http-0-sw1zpr18aml6epqnir0a4o8o.rule=Host(`api.enov360.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-sw1zpr18aml6epqnir0a4o8o.service=http-0-sw1zpr18aml6epqnir0a4o8o
            - traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.entryPoints=https
            - traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.middlewares=gzip
            - 'traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.rule=Host(`api.enov360.com`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.service=https-0-sw1zpr18aml6epqnir0a4o8o
            - traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.tls=true
            - traefik.http.routers.https-0-sw1zpr18aml6epqnir0a4o8o.tls.certresolver=letsencrypt
            - traefik.http.services.http-0-sw1zpr18aml6epqnir0a4o8o.loadbalancer.server.port=3000
            - traefik.http.services.https-0-sw1zpr18aml6epqnir0a4o8o.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://api.enov360.com'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.473
            - coolify.applicationId=3
            - coolify.type=application
            - coolify.name=sw1zpr18aml6epqnir0a4o8o
            - coolify.resourceName=enov-api
            - coolify.projectName=enovait
            - coolify.serviceName=enov-api
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
